name: 'sonarqube-scan'
description: 'Sonarqube analysis of the code'
author: ''
branding:
  icon: 'check'
  color: 'green'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  version:
    description: 'sonar-scanner-version'
    required: false
    default: '4.2.0.1873'
