# This is a basic workflow to help you get started with Actions

name: sonar using github actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: harshit-newzera/my-sonar-action-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
