name: sonar

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup sonarqube
      uses: ./  
    - name: run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
